Update workflowcpp_compilation_check.yml

diff --git a/.github/workflows/workflowcpp_compilation_check.yml b/.github/workflows/workflowcpp_compilation_check.yml
--- a/.github/workflows/workflowcpp_compilation_check.yml
+++ b/.github/workflows/workflowcpp_compilation_check.yml
@@ -16,22 +16,24 @@ jobs:
     - name: Install g++
       run: sudo apt-get install g++ -y
 
-    - name: List files in the working directory
-      run: ls -la
+    - name: Get changed C++ files
+      id: get-files
+      run: |
+        files=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}/files" | jq -r '.[].filename | select(endswith(".cpp"))')
+        echo "$files" > changed_cpp_files.txt
 
     - name: Check for C++ compilation errors
       run: |
         failed_compilations=""
-        for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.cpp$'); do
-          if [ -f "$file" ]; then
-            echo "Compiling $file"
-            g++ -o "${file%.cpp}.out" "$file" 2>&1
-            if [ $? -ne 0 ]; then
-              echo "C++ compilation failed in $file"
-              failed_compilations="${failed_compilations}${file}\n"
-            fi
+        while IFS= read -r file; do
+          echo "Compiling $file"
+          g++ -o "${file%.cpp}.out" "$file" 2>&1
+          if [ $? -ne 0 ]; then
+            echo "C++ compilation failed in $file"
+            failed_compilations="${failed_compilations}${file}\n"
           fi
-        done
+        done < changed_cpp_files.txt
+
         if [ -n "$failed_compilations" ]; then
           echo "The following C++ files failed compilation:"
           echo -e "$failed_compilations"
