Update workflowcpp_compilation_check.yml

diff --git a/.github/workflows/workflowcpp_compilation_check.yml b/.github/workflows/workflowcpp_compilation_check.yml
--- a/.github/workflows/workflowcpp_compilation_check.yml
+++ b/.github/workflows/workflowcpp_compilation_check.yml
@@ -23,11 +23,13 @@ jobs:
       run: |
         failed_compilations=""
         for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.cpp$'); do
-          echo "Compiling $file"
-          g++ -o "${file%.cpp}.out" "$file" 2>&1
-          if [ $? -ne 0 ]; then
-            echo "C++ compilation failed in $file"
-            failed_compilations="${failed_compilations}${file}\n"
+          if [ -f "$file" ]; then
+            echo "Compiling $file"
+            g++ -o "${file%.cpp}.out" "$file" 2>&1
+            if [ $? -ne 0 ]; then
+              echo "C++ compilation failed in $file"
+              failed_compilations="${failed_compilations}${file}\n"
+            fi
           fi
         done
         if [ -n "$failed_compilations" ]; then
